# Generated by Django 4.0 on 2021-12-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateField(verbose_name='Date of creation'),
        ),
    ]
