# Generated by Django 4.0 on 2021-12-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_question_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date of creation'),
        ),
    ]
