# Generated by Django 4.0 on 2021-12-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_question_creation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateField(verbose_name='Date of creation'),
        ),
    ]
